sudo: required
service:
 - docker
before_install:
  - docker build -t ranreply/rrlocal:3.0 .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push ranreply/rrlocal:3.0
notifications:
 email:
   recipients:
     - ranjan.rajendran@gmail.com
   on_success: always
   on_failure: always
